### ISSUE TITLE
How to avoid some availability domains

### ISSUE THREAD

**Issue by valentinvieriu** [GlorifiedTypist/k3s-oracle-cloud-free-tier#2]
Thank you for this script, this a well thought one.
Is there a way to avoid AD-1 from the Instance Pools? At this moment AD-1 in my region ( Frankfurt ) does not have enough resources to spin a VM.

Is there a way to add something similar to the `freetier_ad_list` option but for the Instance Pool?

**Comment by GlorifiedTypist** [comment]
I can add that in. What is the error you are getting so I can add it to the documentation.

**Comment by valentinvieriu** [comment]
`Instance launch failed. (500, InternalError, false) Out of host capacity. (opc-request-id: A0DB436048284D84A473F5DAD1521411/672D0B3BBDFF9F140812275010A1075C/1814257CBB5A6F72ADA3E1D40556A9A1)`

**Comment by GlorifiedTypist** [comment]
@valentinvieriu I have added the PR to resolve this issue. I will merge once I have had a chance to test. Let me know if this resolves you issue?

**Comment by valentinvieriu** [comment]
I've tested it and seems to work, but I've could not finish the install because of #10
