### ISSUE TITLE
attach the 2 Block Volumes Storage, 200 GB total to workloads clusters

### ISSUE THREAD

**Issue by valentinvieriu** [GlorifiedTypist/k3s-oracle-cloud-free-tier#7]
As it seems we get 2 Block Volumes Storage, 200 GB total. Is it possible to attach them to the 2 worker nodes (100GB each )?
I assume this can be used than as PVC in the workers

**Comment by GlorifiedTypist** [comment]
For the free tier there is a total of 200Gb of block storage for the entire account. As we bootstrap a total of 4 instances which have a minimum boot volume of 50Gb (47Gb real) this would run over the free tier usage and move into paid.

I am keeping this at those limits as its about having a totally free k3s cluster. 

_Block Volume
All tenancies receive a total of 200 GB of Block Volume storage, and five volume backups included in the Always Free resources. These amounts apply to both boot volumes and block volumes combined. When you provision a compute instance, the instance automatically receives a 50 GB boot volume for storage. You can also create and attach block volumes to expand the storage capacity of a compute instance. For more information, see Creating a Volume and Attaching a Volume._

More info: [here](https://docs.oracle.com/en-us/iaas/Content/FreeTier/freetier_topic-Always_Free_Resources.htm)

For development I use a hostPath. Storage is cheap enough to use PVC and move out of free tier.

**Comment by valentinvieriu** [comment]
I didn't quite get that the boot volumes are part of this 200GB 
Thank you for the response. Makse

**Comment by axlroden** [comment]
This is why, running 2 arm based instances, and deploying a 105GB block volume seems much better, than these slow free-tier amd cpu cores.
